apiVersion: v1
kind: Pod
metadata:
  name: farmacia_api
  labels:
    app: api-pod
spec:
  containers:
  - name: farmacia_api
    image: duartefull/app-farmacia:1.0:latest
    envFrom:
    - configMapRef:
        name: db-configmap
    ports:
    - containerPort: 8080