apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api-pod
spec:
  containers:
  - name: farmacia-container
    image: duartefull/farmacia:1.2
    envFrom:
    - configMapRef:
        name: api-configmap
    ports:
    - containerPort: 8080