apiVersion: v1
kind: Pod
metadata:
  name: bdpfarm
  labels:
    app: db-pod
spec:
  containers:
  - name: mysql
    image: mysql:lastest
    envFrom:
    - configMapRef:
        name: db-configmap
    ports:
    - containerPort: 3306