apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db-pod
spec:
  containers:
  - name: mysql-container
    image: mysql:latest
    ports:
    - containerPort: 3306
    envFrom:
    - configMapRef:
        name: db-configmap
